version: "3.8"

services:
  # Service untuk aplikasi
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p2-oc-api
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - /app/node_modules
      - .:/app
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - internal_network

  # Service untuk database MySQL
  mysql:
    image: mysql:8.0
    container_name: kelompok6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: 
      MYSQL_USER: dio
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge

volumes:
  mysql_data: