# CATATAN: File ini untuk setup lengkap dengan database eksternal
# Gunakan ini jika container MySQL sudah dijalankan secara manual

version: "3.8"

services:

  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p2-oc-api
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      disable: true
    depends_on: []  # Tidak lagi tergantung pada mysql dari compose
    networks:
      - mysql_network

# Hapus bagian mysql di bawah karena kamu pakai container eksternal

networks:
  mysql_network:
    external: true  # Menggunakan network Docker yang sudah dibuat manual
