# CATATAN: File ini untuk setup lengkap dengan database internal
# Untuk database eksternal, gunakan docker-compose.standalone.yml

services:

  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p2-oc-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - /app/node_modules
    restart: unless-stopped
    networks:
      - p2-oc-network
    healthcheck:
      test: ["CMD", "node", "/app/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  p2-oc-network:
    driver: bridge
